[changelog]
header = "# Changelog\n\nĞ’ÑĞµ Ğ¸Ğ·Ğ¼ĞµĞ½ĞµĞ½Ğ¸Ñ ÑÑ‚Ğ¾Ğ³Ğ¾ Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ğ°.\n"

[git]
conventional_commits = true
filter_unconventional = true

[commit_types]
feat = { title = "ğŸš€ Features" }
fix = { title = "ğŸ› Fixes" }
refactor = { title = "â™» Refactor" }
docs = { title = "ğŸ“š Docs" }
chore = { title = "ğŸ§¹ Chore" }
